import { useState } from 'react';
import Button from '../components/Button';
import Modal from '../components/Modal'

function ModalPage () {
  const [showModal, setShowModal] = useState(false);

  const handleClick = () => {
    setShowModal(true);
  };

  const handleClose = () => {
    setShowModal(false)
  }

  const actionBar =(
    <div>
       <Button onClick={handleClose} primary>I Accept</Button>
    </div>
  )

  const modal = <Modal onClose={handleClose} actionBar={actionBar}>
    <p>
      Here is an important agreement for you to accept
    </p>
  </Modal>

  return (
    <div className='relative'>
      <Button onClick={handleClick} primary>
        Open Modal
      </Button>
      {showModal && modal}
      <h2>Origins</h2>
      <p>
        The concept behind Pokemon was originated by Satoshi Tajiri. Tajiri grew up in Machida, a suburb of Tokyo; and in his youth, enjoyed discovering and catching insects and other small creatures in the various ponds and fields that surrounded his town.[19][20] As Japan's economic miracle began, many cities, including Machida, were significantly expanded, consequently encroaching the nature of the town. In his second year of junior high school,[21][22] an arcade hall opened in Tajiri's neighborhood, and he developed an interest in video games. While studying electrical engineering at Tokyo College of Technology [ja], Tajiri began publishing a doujinshi magazine titled Game Freak.[23] The title was inspired by the 1932 film Freaks, of which Tajiri was a fan.[24] He self-published the first issue of the magazine in March 1983, at the age of 17.[25] [26] At the time, video game magazines were not yet published in Japan, allowing Game Freak to fill a gap in the market.[27][28] Concurrently, Tajiri was contacted by aspiring manga artist Ken Sugimori, who became Game Freak's illustrator.[29] Game Freak folded in the late 1980s,[25] by which point Tajiri had become a respected game journalist in Japan's fledgling video game industry.[30]

        Tajiri's knowledge of video games brought him into contact with Tsunekazu Ishihara. Ishihara had studied Arts and Science at Tsukuba University, and was trained in CGI. After working in advertisement for two years, Ishihara joined a company named Sedic in 1983, which created video graphics and software,[31] including one video game, Otocky (1987).[32][33] As video games became popular, Sedic also produced a number of game-related television shows for Fuji Television's late-night slot.[31] Ishihara, who became a TV producer, befriended Tajiri, as well as Shigesato Itoi, who would later become CEO of Ape, Inc.[34][35] Ishihara was also the general director of the world's first gaming encyclopedia, TV Games: Encyclopedia of Video Games (テレビゲーム―電視遊戯大全, Terebigēmu ― Denshi Yūgi Taizen).[36][37] In 2000, Kenji Hatakeyama & Masakazu Kubo wrote that, at the time, Ishihara was probably the most well-connected man in the industry,[38] with a knowledge of games "beyond comparison".[39] Ishihara was also interested in playing cards,[40][41] and contributed to the development of at least three simple card games designed by Itoi for Ape.[c]

        In 1986, Tajiri, Sugimori, and a small group of fellow enthusiasts started an informal development team, named Game Freak, after the Tajiri's magazine. During the next three years, they independently developed the puzzle game Quinty, working on it alongside school or their other jobs.[48] However, no one within the group could compose its music. After consulting all his contacts, Tajiri came into contact with Junichi Masuda, who became the group's composer.[49] Quinty was finished in 1989, and published by Namco.[50] Tajiri officially incorporated Game Freak Co., Ltd. on April 26, 1989.[51]
      </p>
      <h2>1989 – 1995: Development of Red & Green</h2>
      <p>
        Tajiri began developing ideas for Pokemon as development on Quinty neared its end. During this period, Nintendo announced the handheld Game Boy console. Tajiri learned that the device would have a link port, and with the corresponding Game Link Cable, two Game Boy unites could be connected.[52] Tajiri also remembered an incident while playing Dragon Quest II, in which in-game items of varying rarities randomly appeared, including the rare Mysterious Hat.[d] Tajiri did not encounter any, while Sugimori, who was also playing the game, encountered two. Upon recalling this experience, Tajiri realized that the cable now made it possible to transfer data from one cartridge to another.[53][54][55][56] Until that point, the Game Link Cable was only used for competing.[57] Combining his inspiration with his childhood memories, Tajiri developed his idea into a virtual recreation of these experiences,[58] and an attempt to "regain the world that he had lost".[59] He would later state that the game represents "the story of a boy's summer day".[60]


        Gashapon capsules have been cited as an inspiration for Pokemon.
        Tajiri and his staff began developing a game centered on capturing creatures of differing rarity. Because the Game Boy is a handheld console, these creatures could be exchanged with other players in real life. Once the player caught one of these creatures, it was to be stored in miniaturized form in a special capsule. This facet of the game was inspired by Ultraseven, a tokusatsu show that Tajiri had enjoyed as a child.[61] The series' titular character owns a number of capsules containing miniaturized kaiju, which come out and return to their original sizes when the capsule is thrown into mid-air. Kaiju media were an important influence to the developers, as many Game Freak staff members grew up with them.[54][62] Other cited influences include gashapon, capsules with toy figures in them that can be drawn from vending machines;[63][64] collectible cards, such as baseball cards, Ultraman cards and menko;[65][66][67][68] The Final Fantasy Legend;[69] and petting in Japan, with Tajiri noting that having Pokemon is similar to having pets.[70] Tajiri initially named his project Capsule Monsters, which GF's staff commonly shortened to Capumon.[71] However, Capsule Monsters could not be trademarked, and it was subsequently decided to title the game Pocket Monsters, which was shortened to Pokemon.[71][72] Author Akihito Tomisawa wrote that the Game Freak staff devised with several alternatives, before settling on "Pocket Monsters".[71]

        In March 1989, Nintendo co-founded Ape, Inc. with Itoi. Ape's principal work was Mother (1989), a role-playing game written by Itoi, but it was also founded with the intent to give outside talent a chance to pitch new, innovative games.[40][35] At the time, Ape was housed in the same Kanda-Sudachō office building as Nintendo, located in Tokyo.[73] Ishihara, a friend of both Itoi and Tajiri, was involved with Ape's management and became vice president of the company in 1991.[35][38] Tajiri's relationship with Ishihara prompted the former to present his pitch at Ape's office.[74][75] Present during Tajiri's pitch was Takashi Kawaguchi, who worked at Nintendo's General Affairs Department and was also a manager at Ape.[40][76] Kawaguchi brought the idea to Nintendo president Hiroshi Yamauchi, who reportedly said, "This is it. This is the idea I've been waiting for."[77] Coincidentally, Ishihara had conceived an idea for a game similar to that of Tajiri, and was also discussing it with Ape. The planned title, Toto, involved "using the Game Boy as an insect cage". Game Freak and Ape subsequently agreed to develop their projects as one.[78] According to Tajiri, the two teams initially collaborated on the project, but the work proved difficult, one of the reasons being that Ape was busy developing EarthBound.[79][80] Tajiri eventually figured that "rather than working with Ape, we had to do something on our own, or the project would never get finished".[79] Ape, Inc. was subsequently not credited on the final product.

        The development contract was signed at the beginning of 1990, with a planned delivery of the game in October.[81] Tajiri directed the project, working under Ishihara.[82] Ishihara was the producer – he managed the budget, staff, and work schedule, monitored the game's overall progress, and served as a liaison between Game Freak and Nintendo.[83][78] Ishihara also contributed ideas to the development,[41] and helped with debugging.[84][85] Sugimori was in charge of the graphics and character design.[86] Masuda composed the score and sound effects, and did additional programming.[87] The budget that Nintendo granted to Game Freak was low.[81] Thus, Pocket Monsters was initially planned as a small, compact game, based primarily around Tajiri's core idea of exchanging.[69][88] However, as development progressed, GF's ideas and ambitions for the game grew.[69] It became clear that their idea would not be easy to realize. Sugimori admitted that, at the time, no one on the staff had much knowledge of RPGs.[89] The project was consequently suspended indefinitely. While developing their second game, Smart Ball (1991), Game Freak was commissioned by Nintendo to develop Yoshi (1991), a simple puzzle game, the idea for which was suggested by Ishihara.[90] Yoshi sold over three million copies worldwide,[91] and both Tajiri[92] and Masuda[41] said that this success allowed Game Freak to survive. Over the next three years, GF developed four more games: Magical Tarurūto-kun (1992), Mario & Wario (1993), Nontan to Issho: KuruKuru Puzzle, and Pulseman (both 1994).

        It is commonly stated that development for the initial game took six years.[10][93][94][95][96] This is, in fact, the total time passed from planning to finish—the game did not take six straight years to complete.[97] After the initial development phase in the early 1990s,[98] the staff "tinkered with it from time to time", as Sugimori put it.[99] By October 1992, many Pokemon had already been designed, and a poll was held that month among all staff members to gauge the popularity of the different species. Several more such votes followed to determine collectively which Pokemon should be included.[100] Still, development was largely suspended until the summer of 1994, after the release of Pulseman, upon which Tajiri decided it was time to make a serious effort towards finishing the game.[101] By this point, Game Freak's experience had grown considerably, and many new staff members had joined the company, one of these being Atsuko Nishida, a graphic designer who created Pikachu, among others.[102][103][104] Ishihara used his knowledge of card games to add more depth to the battle system and suggested that the creatures should have types. Ishihara also came up with the idea of the Pokédex, a portable encyclopedia which players can use to keep track of their Pokemon.[41] Throughout the years, Tajiri had several conversations with Shigeru Miyamoto,[105] Nintendo's senior game designer who Tajiri described as a mentor figure.[61] However, in a 2018 retrospect, Miyamoto downplayed his role, and stated that his contributions to Pocket Monsters were limited.[106]

        Both Tajiri and Ishihara sought to 'individualize' the player's experience, to make each game slightly different so as to create a unique experience.[107] At an early stage, Tajiri had the idea of having the software generate a random number on the first playthrough, ranging from 00001 to 65535 (the highest possible value of an unsigned 16-bit integer).[108][109] When a player catches a Pokemon, it is assigned the game's ID and the player's name, which are retained after it is traded.[110] Based on the unique ID, Game Freak intended for the game to render slightly different landscapes and present the player with different Pokemon,[96][109][111] which ultimately proved impossible.[e] When Tajiri discussed these with Miyamoto, the latter opined that it was slightly difficult to understand. Miyamoto also suggested using different colored cartridges, which would make the differences between versions more visually clear.[112] According to Tajiri, "five or seven colors" were considered[113] before they settled on two: a Red version and a Green version. Both games were identical, but each had Pokemon not found in the other, so as to encourage trading between players.[107]

        Ishihara aspired to create games of his own.[114] As Pocket Monsters Red and Green were nearing completion, Ishihara founded Creatures, Inc. on November 8, 1995, originally headquartered in the same Sudachō office building as the Nintendo Kanda Building in Tokyo.[115] Co-ownership of the Pocket Monsters property was subsequently assigned to Creatures. This resulted in the intellectual property having three legal owners: Game Freak, the main developer; Creatures, representing producer Ishihara; and Nintendo, the publisher, which acquired the property upon completion.[116] Hatakeyama & Kubo (2000) wrote that Pocket Monsters is probably the only property in the world today for which the original rights are not concentrated in a single company."[117] Tajiri and Ishihara briefly considered merging Game Freak and Creatures, before Tajiri decided against it, believing that it would erase what he had built up since he was a teenager. "I felt threatened by the idea of changing how Game Freak was operating, and starting back over with Mr. Ishihara", he said. "It was an identity problem. If Game Freak ceased to exist, then so would I". Tajiri noted that, since Game Freak and Creatures both focus on Pocket Monsters, it sometimes felt more like different departments than different companies.[74]

        Development on Pocket Monsters Red and Pocket Monsters Green was completed in December 1995.[118] They were originally announced to release on December 21, 1995,[119] before being delayed to February 27, 1996 after a sufficient amount of cartridges, manuals, and packaging was produced. Copyright notices[6] on merchandise display 1995 as the copyright date, despite no Pokemon product having actually been released that year.
      </p>
    </div>
    
  )
};

export default ModalPage;
